- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tooz-tox-examples
        - tooz-tox-py311-etcd3gw
        - tooz-tox-py313-etcd3gw
        - tooz-tox-py311-zookeeper
        - tooz-tox-py313-zookeeper
        - tooz-tox-py311-redis
        - tooz-tox-py313-redis
        - tooz-tox-py311-sentinel
        - tooz-tox-py313-sentinel
        - tooz-tox-py311-memcached
        - tooz-tox-py313-memcached
        - tooz-tox-py311-postgresql
        - tooz-tox-py313-postgresql
        - tooz-tox-py311-mysql
        - tooz-tox-py313-mysql
        - tooz-tox-py311-consul
        - tooz-tox-py313-consul
    gate:
      jobs:
        - tooz-tox-examples
        - tooz-tox-py311-etcd3gw
        - tooz-tox-py313-etcd3gw
        - tooz-tox-py311-zookeeper
        - tooz-tox-py313-zookeeper
        - tooz-tox-py311-redis
        - tooz-tox-py313-redis
        - tooz-tox-py311-sentinel
        - tooz-tox-py313-sentinel
        - tooz-tox-py311-memcached
        - tooz-tox-py313-memcached
        - tooz-tox-py311-postgresql
        - tooz-tox-py313-postgresql
        - tooz-tox-py311-mysql
        - tooz-tox-py313-mysql
        - tooz-tox-py311-consul
        - tooz-tox-py313-consul

- job:
    name: tooz-tox-examples
    parent: openstack-tox-py312
    description: |
      Run tests using ``examples`` environment.
    vars:
      tox_envlist: examples

- job:
    name: tooz-tox-py311-consul
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-consul`` environment.
    vars:
      tox_envlist: py311-consul

- job:
    name: tooz-tox-py311-etcd3gw
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-etcd3gw`` environment.
    vars:
      tox_envlist: py311-etcd3gw

- job:
    name: tooz-tox-py311-memcached
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-memcached`` environment.
    vars:
      tox_envlist: py311-memcached

- job:
    name: tooz-tox-py311-mysql
    parent: openstack-tox-py311
    # NOTE(tkajinam): Debian Bookworm which is used for py311 tests do not
    # provide mysqld. Because pifpaf does not support mariadb atm we use
    # Ubuntu Noble which provides mysql.
    nodeset: ubuntu-noble
    description: |
      Run tests using ``py311-mysql`` environment.
    vars:
      tox_envlist: py311-mysql
      python_use_pyenv: true

- job:
    name: tooz-tox-py311-postgresql
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-postgresql`` environment.
    vars:
      tox_envlist: py311-postgresql

- job:
    name: tooz-tox-py311-redis
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-redis`` environment.
    vars:
      tox_envlist: py311-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py311-sentinel
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-sentinel`` environment.
    vars:
      tox_envlist: py311-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py311-zookeeper
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-zookeeper`` environment.
    vars:
      tox_envlist: py311-zookeeper

- job:
    name: tooz-tox-py313-consul
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-consul`` environment.
    vars:
      tox_envlist: py313-consul

- job:
    name: tooz-tox-py313-etcd3gw
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-etcd3gw`` environment.
    vars:
      tox_envlist: py313-etcd3gw

- job:
    name: tooz-tox-py313-memcached
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-memcached`` environment.
    vars:
      tox_envlist: py313-memcached

- job:
    name: tooz-tox-py313-mysql
    parent: openstack-tox-py313
    # NOTE(tkajinam): Debian Trixie which is used for py313 tests do not
    # provide mysqld. Because pifpaf does not support mariadb atm we use
    # Ubuntu Noble which provides mysql.
    nodeset: ubuntu-noble
    description: |
      Run tests using ``py313-mysql`` environment.
    vars:
      python_use_pyenv: True
      tox_envlist: py313-mysql

- job:
    name: tooz-tox-py313-postgresql
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-postgresql`` environment.
    vars:
      tox_envlist: py313-postgresql

- job:
    name: tooz-tox-py313-redis
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-redis`` environment.
    vars:
      tox_envlist: py313-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py313-sentinel
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-sentinel`` environment.
    vars:
      tox_envlist: py313-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py313-zookeeper
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-zookeeper`` environment.
    vars:
      tox_envlist: py313-zookeeper
