---

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - openstack-python3-next-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tooz-tox-examples
        - tooz-tox-py311-etcd3gw
        - tooz-tox-py314-etcd3gw
        - tooz-tox-py311-zookeeper
        - tooz-tox-py314-zookeeper
        - tooz-tox-py311-redis
        - tooz-tox-py314-redis
        - tooz-tox-py311-sentinel
        - tooz-tox-py314-sentinel
        - tooz-tox-py311-memcached
        - tooz-tox-py314-memcached
        - tooz-tox-py311-postgresql
        - tooz-tox-py314-postgresql
        - tooz-tox-py311-mysql
        - tooz-tox-py314-mysql
    gate:
      jobs:
        - tooz-tox-examples
        - tooz-tox-py311-etcd3gw
        - tooz-tox-py314-etcd3gw
        - tooz-tox-py311-zookeeper
        - tooz-tox-py314-zookeeper
        - tooz-tox-py311-redis
        - tooz-tox-py314-redis
        - tooz-tox-py311-sentinel
        - tooz-tox-py314-sentinel
        - tooz-tox-py311-memcached
        - tooz-tox-py314-memcached
        - tooz-tox-py311-postgresql
        - tooz-tox-py314-postgresql
        - tooz-tox-py311-mysql
        - tooz-tox-py314-mysql

- job:
    name: tooz-tox-examples
    parent: openstack-tox-py312
    description: |
      Run tests using ``examples`` environment.
    vars:
      tox_envlist: examples

- job:
    name: tooz-tox-py311-etcd3gw
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-etcd3gw`` environment.
    vars:
      tox_envlist: py311-etcd3gw

- job:
    name: tooz-tox-py311-memcached
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-memcached`` environment.
    vars:
      tox_envlist: py311-memcached

- job:
    name: tooz-tox-py311-mysql
    parent: openstack-tox-py311
    # NOTE(tkajinam): Debian Bookworm which is used for py311 tests do not
    # provide mysqld. Because pifpaf does not support mariadb atm we use
    # Ubuntu Noble which provides mysql.
    nodeset: ubuntu-noble
    description: |
      Run tests using ``py311-mysql`` environment.
    vars:
      tox_envlist: py311-mysql
      python_use_pyenv: True

- job:
    name: tooz-tox-py311-postgresql
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-postgresql`` environment.
    vars:
      tox_envlist: py311-postgresql

- job:
    name: tooz-tox-py311-redis
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-redis`` environment.
    vars:
      tox_envlist: py311-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py311-sentinel
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-sentinel`` environment.
    vars:
      tox_envlist: py311-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py311-zookeeper
    parent: openstack-tox-py311
    description: |
      Run tests using ``py311-zookeeper`` environment.
    vars:
      tox_envlist: py311-zookeeper

- job:
    name: tooz-tox-py314-etcd3gw
    parent: openstack-tox-py314
    description: |
      Run tests using ``py314-etcd3gw`` environment.
    vars:
      tox_envlist: py314-etcd3gw

- job:
    name: tooz-tox-py314-memcached
    parent: openstack-tox-py314
    description: |
      Run tests using ``py314-memcached`` environment.
    vars:
      tox_envlist: py314-memcached

- job:
    name: tooz-tox-py314-mysql
    parent: openstack-tox-py314
    # NOTE(tkajinam): Debian Trixie which is used for py314 tests do not
    # provide mysqld. Because pifpaf does not support mariadb atm we use
    # Ubuntu Noble which provides mysql.
    nodeset: ubuntu-noble
    description: |
      Run tests using ``py314-mysql`` environment.
    vars:
      python_use_pyenv: True
      tox_envlist: py314-mysql

- job:
    name: tooz-tox-py314-postgresql
    parent: openstack-tox-py314
    description: |
      Run tests using ``py314-postgresql`` environment.
    vars:
      tox_envlist: py314-postgresql

- job:
    name: tooz-tox-py314-redis
    parent: openstack-tox-py314
    description: |
      Run tests using ``py314-redis`` environment.
    vars:
      tox_envlist: py314-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py314-sentinel
    parent: openstack-tox-py314
    description: |
      Run tests using ``py314-sentinel`` environment.
    vars:
      tox_envlist: py314-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py314-zookeeper
    parent: openstack-tox-py314
    description: |
      Run tests using ``py314-zookeeper`` environment.
    vars:
      tox_envlist: py314-zookeeper
