- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tooz-tox-py310-etcd3gw
        - tooz-tox-py312-etcd3gw
        - tooz-tox-py310-zookeeper
        - tooz-tox-py312-zookeeper
        - tooz-tox-py310-redis
        - tooz-tox-py312-redis
        - tooz-tox-py310-sentinel
        - tooz-tox-py312-sentinel
        - tooz-tox-py310-memcached
        - tooz-tox-py312-memcached
        - tooz-tox-py310-postgresql
        - tooz-tox-py312-postgresql
        - tooz-tox-py310-mysql
        - tooz-tox-py312-mysql
        - tooz-tox-py310-consul
        - tooz-tox-py312-consul
    gate:
      jobs:
        - tooz-tox-py310-etcd3gw
        - tooz-tox-py312-etcd3gw
        - tooz-tox-py310-zookeeper
        - tooz-tox-py312-zookeeper
        - tooz-tox-py310-redis
        - tooz-tox-py312-redis
        - tooz-tox-py310-sentinel
        - tooz-tox-py312-sentinel
        - tooz-tox-py310-memcached
        - tooz-tox-py312-memcached
        - tooz-tox-py310-postgresql
        - tooz-tox-py312-postgresql
        - tooz-tox-py310-mysql
        - tooz-tox-py312-mysql
        - tooz-tox-py310-consul
        - tooz-tox-py312-consul

- job:
    name: tooz-tox-py310-consul
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-consul`` environment.
    vars:
      tox_envlist: py310-consul

- job:
    name: tooz-tox-py310-etcd3gw
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-etcd3gw`` environment.
    vars:
      tox_envlist: py310-etcd3gw

- job:
    name: tooz-tox-py310-memcached
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-memcached`` environment.
    vars:
      tox_envlist: py310-memcached

- job:
    name: tooz-tox-py310-mysql
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-mysql`` environment.
    vars:
      tox_envlist: py310-mysql

- job:
    name: tooz-tox-py310-postgresql
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-postgresql`` environment.
    vars:
      tox_envlist: py310-postgresql

- job:
    name: tooz-tox-py310-redis
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-redis`` environment.
    vars:
      tox_envlist: py310-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py310-sentinel
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-sentinel`` environment.
    vars:
      tox_envlist: py310-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py310-zookeeper
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-zookeeper`` environment.
    vars:
      tox_envlist: py310-zookeeper

- job:
    name: tooz-tox-py312-consul
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-consul`` environment.
    vars:
      tox_envlist: py312-consul

- job:
    name: tooz-tox-py312-etcd3gw
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-etcd3gw`` environment.
    vars:
      tox_envlist: py312-etcd3gw

- job:
    name: tooz-tox-py312-memcached
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-memcached`` environment.
    vars:
      tox_envlist: py312-memcached

- job:
    name: tooz-tox-py312-mysql
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-mysql`` environment.
    vars:
      tox_envlist: py312-mysql

- job:
    name: tooz-tox-py312-postgresql
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-postgresql`` environment.
    vars:
      tox_envlist: py312-postgresql

- job:
    name: tooz-tox-py312-redis
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-redis`` environment.
    vars:
      tox_envlist: py312-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py312-sentinel
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-sentinel`` environment.
    vars:
      tox_envlist: py312-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py312-zookeeper
    parent: openstack-tox-py312
    description: |
      Run tests using ``py312-zookeeper`` environment.
    vars:
      tox_envlist: py312-zookeeper
