- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tooz-tox-py310-etcd3gw
        - tooz-tox-py313-etcd3gw
        - tooz-tox-py310-zookeeper
        - tooz-tox-py313-zookeeper
        - tooz-tox-py310-redis
        - tooz-tox-py313-redis
        - tooz-tox-py310-sentinel
        - tooz-tox-py313-sentinel
        - tooz-tox-py310-memcached
        - tooz-tox-py313-memcached
        - tooz-tox-py310-postgresql
        - tooz-tox-py313-postgresql
        - tooz-tox-py310-mysql
        - tooz-tox-py313-mysql
        - tooz-tox-py310-consul
        - tooz-tox-py313-consul
    gate:
      jobs:
        - tooz-tox-py310-etcd3gw
        - tooz-tox-py313-etcd3gw
        - tooz-tox-py310-zookeeper
        - tooz-tox-py313-zookeeper
        - tooz-tox-py310-redis
        - tooz-tox-py313-redis
        - tooz-tox-py310-sentinel
        - tooz-tox-py313-sentinel
        - tooz-tox-py310-memcached
        - tooz-tox-py313-memcached
        - tooz-tox-py310-postgresql
        - tooz-tox-py313-postgresql
        - tooz-tox-py310-mysql
        - tooz-tox-py313-mysql
        - tooz-tox-py310-consul
        - tooz-tox-py313-consul

- job:
    name: tooz-tox-py310-consul
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-consul`` environment.
    vars:
      tox_envlist: py310-consul

- job:
    name: tooz-tox-py310-etcd3gw
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-etcd3gw`` environment.
    vars:
      tox_envlist: py310-etcd3gw

- job:
    name: tooz-tox-py310-memcached
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-memcached`` environment.
    vars:
      tox_envlist: py310-memcached

- job:
    name: tooz-tox-py310-mysql
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-mysql`` environment.
    vars:
      tox_envlist: py310-mysql

- job:
    name: tooz-tox-py310-postgresql
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-postgresql`` environment.
    vars:
      tox_envlist: py310-postgresql

- job:
    name: tooz-tox-py310-redis
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-redis`` environment.
    vars:
      tox_envlist: py310-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py310-sentinel
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-sentinel`` environment.
    vars:
      tox_envlist: py310-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py310-zookeeper
    parent: openstack-tox-py310
    description: |
      Run tests using ``py310-zookeeper`` environment.
    vars:
      tox_envlist: py310-zookeeper

- job:
    name: tooz-tox-py313-consul
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-consul`` environment.
    vars:
      tox_envlist: py313-consul

- job:
    name: tooz-tox-py313-etcd3gw
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-etcd3gw`` environment.
    vars:
      tox_envlist: py313-etcd3gw

- job:
    name: tooz-tox-py313-memcached
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-memcached`` environment.
    vars:
      tox_envlist: py313-memcached

- job:
    name: tooz-tox-py313-mysql
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-mysql`` environment.
    vars:
      tox_envlist: py313-mysql

- job:
    name: tooz-tox-py313-postgresql
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-postgresql`` environment.
    vars:
      tox_envlist: py313-postgresql

- job:
    name: tooz-tox-py313-redis
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-redis`` environment.
    vars:
      tox_envlist: py313-redis
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py313-sentinel
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-sentinel`` environment.
    vars:
      tox_envlist: py313-sentinel
    pre-run:
      - playbooks/stop-redis.yaml

- job:
    name: tooz-tox-py313-zookeeper
    parent: openstack-tox-py313
    description: |
      Run tests using ``py313-zookeeper`` environment.
    vars:
      tox_envlist: py313-zookeeper
