"""Type stubs for the sysv_ipc C extension module."""

import sys
from types import TracebackType

# Module-level constants
PAGE_SIZE: int
KEY_MIN: int
KEY_MAX: int
SEMAPHORE_VALUE_MAX: int
SEMAPHORE_TIMEOUT_SUPPORTED: bool

IPC_CREAT: int
IPC_EXCL: int
IPC_CREX: int
IPC_PRIVATE: int

SHM_RND: int
SHM_RDONLY: int

if sys.platform == "linux":
    SHM_HUGETLB: int
    SHM_NORESERVE: int
    SHM_REMAP: int

VERSION: str
__version__: str
__author__: str
__copyright__: str
__license__: str

# Exceptions

class Error(Exception): ...
class InternalError(Error): ...
class PermissionsError(Error): ...
class ExistentialError(Error): ...
class BusyError(Error): ...
class NotAttachedError(Error): ...

class Semaphore:
    # Read-only members/properties
    id: int
    @property
    def key(self) -> int: ...
    @property
    def last_pid(self) -> int: ...
    @property
    def waiting_for_nonzero(self) -> int: ...
    @property
    def waiting_for_zero(self) -> int: ...
    @property
    def o_time(self) -> int: ...
    @property
    def cuid(self) -> int: ...
    @property
    def cgid(self) -> int: ...

    # Read-write properties
    @property
    def value(self) -> int: ...
    @value.setter
    def value(self, v: int) -> None: ...
    @property
    def undo(self) -> bool: ...
    @undo.setter
    def undo(self, v: bool) -> None: ...
    @property
    def block(self) -> bool: ...
    @block.setter
    def block(self, v: bool) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, v: int) -> None: ...
    @property
    def uid(self) -> int: ...
    @uid.setter
    def uid(self, v: int) -> None: ...
    @property
    def gid(self) -> int: ...
    @gid.setter
    def gid(self, v: int) -> None: ...
    def __init__(
        self,
        key: int | None,
        flags: int = 0,
        mode: int = 0o600,
        initial_value: int = 0,
    ) -> None: ...
    def acquire(
        self,
        timeout: float | None = None,
        delta: int = -1,
    ) -> None: ...
    def P(
        self,
        timeout: float | None = None,
        delta: int = -1,
    ) -> None: ...
    def release(self, delta: int = 1) -> None: ...
    def V(self, delta: int = 1) -> None: ...
    def Z(self, timeout: float | None = None) -> None: ...
    def remove(self) -> None: ...
    def __enter__(self) -> Semaphore: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...

class SharedMemory:
    # Read-only members/properties
    id: int
    @property
    def key(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def address(self) -> int: ...
    @property
    def attached(self) -> bool: ...
    @property
    def last_attach_time(self) -> int: ...
    @property
    def last_detach_time(self) -> int: ...
    @property
    def last_change_time(self) -> int: ...
    @property
    def creator_pid(self) -> int: ...
    @property
    def last_pid(self) -> int: ...
    @property
    def number_attached(self) -> int: ...
    @property
    def cuid(self) -> int: ...
    @property
    def cgid(self) -> int: ...

    # Read-write properties
    @property
    def uid(self) -> int: ...
    @uid.setter
    def uid(self, v: int) -> None: ...
    @property
    def gid(self) -> int: ...
    @gid.setter
    def gid(self, v: int) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, v: int) -> None: ...
    def __init__(
        self,
        key: int | None,
        flags: int = 0,
        mode: int = 0o600,
        size: int = 0,
        init_character: bytes = b" ",
    ) -> None: ...
    def read(self, byte_count: int = 0, offset: int = 0) -> bytes: ...
    def write(self, s: bytes, offset: int = 0) -> None: ...
    def attach(self, address: int | None = None, flags: int = 0) -> None: ...
    def detach(self) -> None: ...
    def remove(self) -> None: ...

class MessageQueue:
    # Read-only members/properties
    id: int
    @property
    def key(self) -> int: ...
    @property
    def last_send_time(self) -> int: ...
    @property
    def last_receive_time(self) -> int: ...
    @property
    def last_change_time(self) -> int: ...
    @property
    def current_messages(self) -> int: ...
    @property
    def last_send_pid(self) -> int: ...
    @property
    def last_receive_pid(self) -> int: ...
    @property
    def cuid(self) -> int: ...
    @property
    def cgid(self) -> int: ...

    # Read-write properties
    @property
    def max_size(self) -> int: ...
    @max_size.setter
    def max_size(self, v: int) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, v: int) -> None: ...
    @property
    def uid(self) -> int: ...
    @uid.setter
    def uid(self, v: int) -> None: ...
    @property
    def gid(self) -> int: ...
    @gid.setter
    def gid(self, v: int) -> None: ...
    def __init__(
        self,
        key: int | None,
        flags: int = 0,
        mode: int = 0o600,
        max_message_size: int = ...,
    ) -> None: ...
    def send(
        self,
        message: bytes,
        block: bool = True,
        type: int = 1,
    ) -> None: ...
    def receive(
        self,
        block: bool = True,
        type: int = 0,
    ) -> tuple[bytes, int]: ...
    def remove(self) -> None: ...

# Module-level functions

def attach(
    id: int,
    address: int | None = None,
    flags: int = 0,
) -> SharedMemory: ...
def ftok(path: str, id: int, silence_warning: bool = False) -> int: ...
def remove_semaphore(id: int) -> None: ...
def remove_shared_memory(id: int) -> None: ...
def remove_message_queue(id: int) -> None: ...
